learning_log/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('users.urls', namespace = 'users')),
    url(r'', include('learning_logs.urls', namespace = 'learning_logs')),
   
]

learning_logs/urls.py
'''Defines URL patterns for learning_logs.'''

from django.conf.urls import url

from . import views

urlpatterns = [
	#Home Page
	url(r'^$', views.index, name = 'index'),
	#Show all Topics
	url(r'^topics/$', views.topics, name = 'topics'),
	#SHow an Individual Topic
	url(r'^topics/(?P<topic_id>\d+)/$', views.topic, name = 'topic'),
	#Page for Adding a new Topic
	url(r'^new_topic/$', views.new_topic, name = 'new_topic'),
	#Page for Adding a New Entry
	url(r'^new_entry/(?P<topic_id>\d+)$', views.new_entry, name = 'new_entry'),
	#Page to Edit Entry
	url(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry, name = 'edit_entry'),
	#Page showing Public Topics
	url(r'^public/$', views.public, name = 'public'),
	#Switches Public setting on a topic
	url(r'^switch/(?P<topic_id>\d+)$', views.switch, name = 'switch'),
]

users/urls.py
'''Defines URL Patterns for Users'''
from django.conf.urls import url
from django.contrib.auth.views import login

from . import views

urlpatterns = [
    #Login Page
    url(r'^login/$', login, {'template_name': 'users/login.html'}, name = 'login'),
    #log out user and return to homepage
    url(r'^logout/$', views.logout_view, name = 'logout'),
    #Page to resgister new user
    url(r'^register/$', views.register, name = 'register'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

class Topic(models.Model):
	'''A topic the user is learning about'''
	text = models.CharField(max_length=200)
	date_added = models.DateTimeField(auto_now_add=True)
	owner = models.ForeignKey(User)
	public = models.BooleanField(default=False)

	def __str__(self):
		'''Return a string representation of the model'''
		return self.text

class Entry(models.Model):
	'''Something Specific learned about a Topic'''
	topic = models.ForeignKey(Topic)
	text = models.TextField()
	date_added = models.DateTimeField(auto_now_add=True)
	owner = models.ForeignKey(User)

	class Meta:
		verbose_name_plural = 'entries'

	def __str__(self):
		'''Return a String representation of the model'''
		if len(self.text) > 50:
			return self.text[:50]+"..."
		else:
			return self.text	

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import  forms

from .models import Topic, Entry

class TopicForm(forms.ModelForm):
	class Meta:
		model = Topic
		fields = ['text', 'public',]
		labels = {'text':'', 'public':'Check here to make this Topic Public'}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text':''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, Http404
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required


from .models import Topic, Entry
from .forms import TopicForm, EntryForm


def index(request):
	'''The Homepage for Learning Log'''
	return render(request, 'learning_logs/index.html')

@login_required
def topics(request):
	'''Displays all topics'''
	topics = Topic.objects.filter(owner=request.user).order_by('date_added')
	context ={'topics':topics}

	return render(request, 'learning_logs/topics.html', context)

@login_required
def topic(request, topic_id):
	'''Displays a Specific Topic Page with all entries'''
	topic = get_object_or_404(Topic, id=topic_id)
	#make sure topic belongs to user
	check_topic_owner(request, topic.owner, topic.public)

	entries = topic.entry_set.order_by('-date_added')

	context = {'topic':topic, 'entries':entries}
	return render(request, 'learning_logs/topic.html', context)

@login_required
def new_topic(request):
	'''Add a new topic'''
	if request.method != 'POST':
		#no data submitted; create a blank form
		form = TopicForm()
	else:
		#POST data submitted; process data
		form = TopicForm(request.POST)
		if form.is_valid():
			new_topic = form.save(commit = False)
			new_topic.owner = request.user
			new_topic.save()
			return HttpResponseRedirect(reverse('learning_logs:topics'))

	context = {'form':form}
	return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
	"""Add a new Entry for a particular topic"""
	topic = get_object_or_404(Topic, id = topic_id)
	check_topic_owner(request, topic.owner, topic.public)

	if request.method != 'POST':
		#No Data Submitted; create a blank form
		form = EntryForm()
	else:
		#POST data submitted; process data.
		form = EntryForm(data = request.POST)
		if form.is_valid():
			new_entry = form.save(commit=False)
			new_entry.topic = topic
			new_entry.owner = request.user
			new_entry.save()
			return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic_id]))
	
	context = {'topic': topic, 'form': form}
	return render(request, 'learning_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
	'''Edit an Existing Entry'''
	entry = get_object_or_404(Entry, id = entry_id)
	topic = entry.topic
	#Makes sure only the Owner can access
	check_topic_owner(request, topic.owner, topic.public)

	if request.method != 'POST':
		#Initial Request; Pre fill form with current Entry
		form = EntryForm(instance=entry)
	else:
		#POST data submitted; process data
		form = EntryForm(instance=entry, data = request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('learning_logs:topic', args = [topic.id]))
	
	context = {'entry':entry, 'topic':topic, 'form': form}
	return render(request, 'learning_logs/edit_entry.html', context)

def check_topic_owner(request, owner, public):
	#Make Sure the User as Access
	if owner != request.user and public == False:
		raise Http404

def public(request):
	'''Displays all Public Topics'''
	topics = Topic.objects.filter(public=True).order_by("date_added")

	context = {'topics':topics}

	return render(request, 'learning_logs/public.html', context)

@login_required
def switch(request, topic_id):
	'''Switches Public Boolean on a specific topic'''
	topic = get_object_or_404(Topic, id=topic_id)
	if topic.owner != request.user:
		raise Http404

	if topic.public == True:
		#Switch Public to False
		topic.public =False
	else:
		topic.public = True

	topic.save()
	return HttpResponseRedirect(reverse('learning_logs:topics'))

	

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm 


def logout_view(request):
    '''Logout the Current User'''
    logout(request)
    return HttpResponseRedirect(reverse('learning_logs:index'))

def register(request):
    '''Page to create a new user'''
    if request.method != 'POST':
        #Display a blank Registration form
        form = UserCreationForm()
    
    else:
        #Process completed
        form = UserCreationForm(data = request.POST)
        if form.is_valid():
            new_user = form.save()
            #Log the User in and return to home page
            authenticated_user = authenticate(username=new_user.username, 
                password = request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('learning_logs:index'))

    context ={'form':form}
    return render(request, 'users/register.html', context)

learning_logs/templates/learning_logs/base.html
{% load bootstrap3 %}

<!DOCTYPE html>

<html lang = "en">
		<head>
			<meta charset = "utf-8">
			<meta http-equiv="X-UA-Compatible" content = "IE=edge">
			<meta name = "viewport" content = "width=device-width, initial-scale=1">

			<title>Learning Log</title>
			<style>
				.bg-1 { 
					 background-color: #ADD8E6; /* Light Blue */
				}
			</style>
			{% bootstrap_css %}
			{% bootstrap_javascript %}
		</head>

		<body>
			<!-- Static navbar -->

			<nav class="navbar bg-1 navbar-default navbar-static-top">
				<div class = "container bg-1">

					<div class="navbar-header">
						<button type = "button" class = "navbar-toggle collapsed"
							data-toggle="collapse" data-target="#navbar"
							aria-expanded="false" aria-controls="navbar">
						Navigation</button>
						<a class="navbar-brand" href="{% url 'learning_logs:index' %}">
							Lessons Learned</a>
					</div>
					
					<div id="navbar" class = "navbar-collapse collapse">
						<ul class="nav navbar-nav">
							<li><a href="{% url 'learning_logs:topics' %}">Your Topics</a></li>
							<li><a href="{% url 'learning_logs:public' %}">Public Topics</a></li>
						</ul>

						<ul class="nav navbar-nav navbar-right">
							{% if user.is_authenticated %}
								<li><a>Hello, {{ user.username }}. </a></li>
								<li><a href="{% url 'users:logout' %}">Log out</a></li>
							{% else %}
								<li><a href = "{% url 'users:login' %}">Log In</a></li>
								<li><a href="{% url 'users:register' %}">Create New User</a></li>
							{% endif %}
						</ul>
					</div><!--/.nav-collapse -->
				
				</div>
			</nav>

			<div class="container">
					<div class="page-header">
						{% block header %}{% endblock header %}
					</div>
					<div>
						{% block content %}{% endblock content %}
					</div>
			</div><!-- /container -->
		</body>
</html>	

learning_logs/templates/learning_logs/edit_entry.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap3 %}

{% block header %}
    <h2>Edit Entry on 
        <a href="{% url 'learning_logs:topic' topic.id %}">{{topic}}</a>
    </h2>
{% endblock header %}

{% block content %}

<form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post' class ="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    
    {% buttons %}
    <button name="submit" class = "btn btn-primary">Save Changes</button>
    {% endbuttons %}
</form>

{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block header %}
  <div class="jumbotron">
    <h1> Track your learning.</h1>
  </div>
{% endblock header %}

{% block content %}
  <h2>
    <a href="{% url 'users:register' %}">Register an account</a> to make
    your own Learning Log and track the topics you're learning about.
  </h2>
  <h2>
    Whenever you learn something new about a topic, you can make an entry
    summarizing what you've learned.
    <br><br>
    You can also create Public Topics that anyone can add entries to. 
  </h2>


{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap3 %}

{% block header %}
    <h2>
        Add a new entry for 
        <a href = "{% url 'learning_logs:topic' topic.id %}">{{topic}}</a>.
    </h2>
{% endblock header %}

{% block content %}

<form action = "{% url 'learning_logs:new_entry' topic.id %}" method='post' class = "form">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
    <button name="submit" class = "btn btn-primary">add entry</button>
    {% endbuttons %}
</form>

{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap3 %}

{% block header %}
	<h2>Add a new Topic:</h2>
{% endblock header %}

{% block content %}

<form action="{% url 'learning_logs:new_topic' %}" method = 'post' class = "form">
	{% csrf_token %}
	{% bootstrap_form form %}

	{% buttons %}
	<button name ="submit" class ="btn btn-primary">add topic</button>
	{% endbuttons %}
	
</form>

{% endblock content %}

learning_logs/templates/learning_logs/public.html
{% extends 'learning_logs/base.html' %}

{% block header %}
  <h2>Public Topics</h2>
{% endblock header %}

{% block content %}

  <ul>
    {% for topic in topics %}
      <li>
        <h3>
            <a href="{% url 'learning_logs:topic' topic.id %}">{{topic}}</a>
            <small>
              created by {{topic.owner}}
            </small>
        </h3>
      </li>
    {% empty %}
      <h1>There aren't any Public Topics Yet</h1>
    {% endfor %}
  </ul>

{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block header %}
	<h2>
		{{ topic|title }}
		{% if topic.public == True %}
			<small>
				(Public)
			</small>
		{% else %}
			<small>
				(Private)
			</small>
		{% endif %}
	</h2>
{% endblock header %}


{% block content %}

<p>
<a href="{% url 'learning_logs:new_entry' topic.id %}">add a new entry</a>
</p>


{% for entry in entries %}
	<div class="panel panel-default">
			<div class="panel-heading">
				<h3>
					On {{ entry.date_added|date:"M d, Y" }} at {{ entry.date_added|time:"H:i" }} <b>{{entry.owner}}</b> wrote:
				</h3>
			</div>
			<div class = "panel-body">
				{{ entry.text|linebreaks }}
				<a href = "{% url 'learning_logs:edit_entry' entry.id %}">edit entry</a>
			</div>
	</div><!-- panel -->

{% empty %}
		There are no Entries for this Topic yet.
{% endfor %}

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block header %}
	<h2>Your Topics
		<small>
			<a href = "{% url 'learning_logs:new_topic' %}">Add a New Topic</a>
		</small>
	</h2>
{% endblock header %}

{% block content %}
	<h2>Private Topics:</h2>
	<ul>
		{% for topic in topics %}
			{% if topic.public == False %}
				<li>
					<h3>
						<a href = "{% url 'learning_logs:topic' topic.id %}"> {{topic}} </a>
						<small>
							<a href="{% url 'learning_logs:switch' topic.id %}">Switch to Public</a>
						</small>
					</h3>
				</li>
			{% endif %}
		{% empty %}
			<li>No topics have been added yet.</li>
		{% endfor %}
	</ul>
	
	<h2>Public Topics:</h2>
	<ul>
		{% for topic in topics %}
			{% if topic.public == True %}
				<li>
					<h3>
						<a href = "{% url 'learning_logs:topic' topic.id %}"> {{topic}} </a>
						<small>
							<a href="{% url 'learning_logs:switch' topic.id %}">Switch to Private</a>
						</small>
					</h3>
				</li>
			{% endif %}
		{% empty %}
			<li>No topics have been added yet.</li>
		{% endfor %}
	</ul>
	

<h3>
	
</h3>

{% endblock content %}

users/templates/users/login.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap3 %}

{% block header %}
    <h2>Log into your account.</h2>
{% endblock header %}

{% block content %}

    <form method = "post" action = "{% url 'users:login' %}" class = "form">
        {% csrf_token %}
        
        {% bootstrap_form form %}
        
        {% buttons %}
        <button name = "submit" class = "btn btn-primary">Log In</button>
        {% endbuttons %}

        <input type = "hidden" name = 'next' value = "{% url 'learning_logs:index' %}" />
    </form>

{% endblock content %}

users/templates/users/register.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap3 %}

{% block header %}
  <h2>
    Create a New User.
  </h2>
{% endblock header %}

{% block content %}

<form method = 'post' action = "{% url 'users:register' %}" class="form">
  {% csrf_token %}
  {% bootstrap_form form %}

  {% buttons %}  
  <button name = "submit" class="btn btn-primary">Create User</button>
  {% endbuttons %}
  <input type ="hidden" name = "next" value = "{% url 'learning_logs:index' %}" />
</form>

{% endblock content %}